add more tests, fix a bug and handle max + 1 records
file.read_exact() sometimes fails with:

thread 'tests::test_max_records' panicked at src/lib.rs:125:45:
called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }

This needs to be fixed.